name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  # Mova para cá
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4  # Versão mais recente
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry
        echo "::add-path::$(python -m poetry config virtualenvs.path)"
        
    - name: Install dependencies
      run: poetry install  # Uso do comando direto

    - name: Test
      run: poetry run python manage.py test
