name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install --upgrade poetry

    - name: Configure Git for Python
      run: |
        echo "Setting up Git executable path"
        export GIT_PYTHON_GIT_EXECUTABLE=$(which git)
      shell: bash

    - name: Install dependencies
      run: poetry install

    - name: Test
      run: poetry run python manage.py test
